-- =========================================================================
-- RETIRED (2026-08-09, user decision): seeded 4 demo checklist templates
-- (Food/Chemical/Fire/Hygiene Safety, 56 items) from chicklist.xlsx, plus
-- their check_checklist_items links to a legacy ISO22000/HACCP/CS/CC/FS/
-- EP/OS demo test bundle. Retired the same way 006_seed_frameworks.sql
-- was: kept resurrecting after being explicitly deleted from production,
-- because scripts/migrate.mjs re-applies every sql/*.sql file on every
-- deploy. Content replaced with a no-op, numbering kept intact. See also
-- 004_seed_checklist.sql, retired for the same reason.
-- =========================================================================
SELECT 1;
