-- =========================================================================
-- RETIRED (2026-08-05, user decision): this file used to seed IT-DOM /
-- HR-DOM / ECS-DOM plus 18 IT-FW-*/HR-FW-* placeholder frameworks on every
-- deploy via ON CONFLICT DO NOTHING/UPDATE. The real GRC now comes from
-- the SOP_GRC_Department_Branch workbook import (Customer Experience
-- Division), and the re-seeding kept resurrecting this old placeholder
-- data after every deploy — including once after it had been explicitly
-- wiped from production. Kept as a no-op so the numbered migration
-- sequence stays intact. See also 031/033/034/036/037, retired the same
-- way and for the same reason.
-- =========================================================================
SELECT 1;
