-- =========================================================================
-- Seed the 79 IT/HR controls from framework.xlsx. Each row keys by code
-- and resolves its framework_id by joining frameworks.code. UPSERT so
-- re-running keeps name + framework in sync if the spreadsheet changes.
-- Frameworks that don't yet exist (partial env) are silently skipped.
-- =========================================================================

INSERT INTO controls (code, name, framework_id, is_active)
SELECT v.code, v.name, f.id, TRUE FROM (VALUES
  ('IT-INFO-CTRL-001', 'Access Rights & Permissions Control', 'IT-FW-001'),
  ('IT-INFO-CTRL-002', 'Data Loss Prevention Incident Control', 'IT-FW-001'),
  ('IT-INFO-CTRL-003', 'Document Retention & Disposal Control', 'IT-FW-001'),
  ('IT-INFO-CTRL-004', 'Encryption Key Management Control', 'IT-FW-001'),
  ('IT-INFO-CTRL-005', 'Information Security Incident Tracking Control', 'IT-FW-001'),
  ('IT-NET-CTRL-001', 'DDoS Mitigation Control', 'IT-FW-002'),
  ('IT-NET-CTRL-002', 'Network Access Control', 'IT-FW-002'),
  ('IT-NET-CTRL-003', 'Network Security Risk Mitigation Control', 'IT-FW-002'),
  ('IT-NET-CTRL-004', 'Network Traffic Monitoring Control', 'IT-FW-002'),
  ('IT-NET-CTRL-005', 'Security Event Correlation Control', 'IT-FW-002'),
  ('IT-CLOUD-CTRL-001', 'Cloud Access Control', 'IT-FW-003'),
  ('IT-CLOUD-CTRL-002', 'Cloud Asset Inventory Control', 'IT-FW-003'),
  ('IT-CLOUD-CTRL-003', 'Cloud Backup & Recovery Testing Control', 'IT-FW-003'),
  ('IT-CLOUD-CTRL-004', 'Cloud Incident Response Control', 'IT-FW-003'),
  ('IT-CLOUD-CTRL-005', 'Cloud Security Configuration Baseline Control', 'IT-FW-003'),
  ('IT-APP-CTRL-001', 'Application Data Encryption Control', 'IT-FW-004'),
  ('IT-APP-CTRL-002', 'Application Threat Modeling Control', 'IT-FW-004'),
  ('IT-APP-CTRL-003', 'Patch & Update Control', 'IT-FW-004'),
  ('IT-APP-CTRL-004', 'Secure Coding Control', 'IT-FW-004'),
  ('IT-APP-CTRL-005', 'Secure Mobile App Testing Control', 'IT-FW-004'),
  ('IT-PROB-CTRL-001', 'Known Error Record Control', 'IT-FW-005'),
  ('IT-PROB-CTRL-002', 'Major Problem Reporting Control', 'IT-FW-005'),
  ('IT-PROB-CTRL-003', 'Problem Management Process Control', 'IT-FW-005'),
  ('IT-PROB-CTRL-004', 'Problem Record Control', 'IT-FW-005'),
  ('IT-PROB-CTRL-005', 'ISMS Problem Escalation Control', 'IT-FW-005'),
  ('IT-SEC-CTRL-001', 'Password Policy Control', 'IT-FW-006'),
  ('IT-SEC-CTRL-002', 'Backup and Recovery Policy Control', 'IT-FW-006'),
  ('IT-SEC-CTRL-003', 'IT Compliance Management Control', 'IT-FW-006'),
  ('IT-SEC-CTRL-004', 'Disposal and Destruction Control', 'IT-FW-006'),
  ('IT-SEC-CTRL-005', 'Information Transfer Control', 'IT-FW-006'),
  ('IT-INC-CTRL-001', 'Incident Management Guide Control', 'IT-FW-007'),
  ('IT-INC-CTRL-002', 'Incident Management Policy Control', 'IT-FW-007'),
  ('IT-INC-CTRL-003', 'Major Incident Report Control', 'IT-FW-007'),
  ('IT-INC-CTRL-004', 'Structural Damage Incident Report Control', 'IT-FW-007'),
  ('IT-INC-CTRL-005', 'Internal Incident Report Control', 'IT-FW-007'),
  ('HR-PREP-CTRL-001', 'Audit Scope and Objectives Control', 'HR-FW-001'),
  ('HR-PREP-CTRL-002', 'Audit Schedule Control', 'HR-FW-001'),
  ('HR-PREP-CTRL-003', 'Audit Roles and Responsibilities Control', 'HR-FW-001'),
  ('HR-PREP-CTRL-004', 'HR Documentation and Sensitive Data Handling Control', 'HR-FW-001'),
  ('HR-COMP-CTRL-001', 'Employment Law Compliance Control', 'HR-FW-002'),
  ('HR-COMP-CTRL-002', 'Benefits Legal Compliance Control', 'HR-FW-002'),
  ('HR-COMP-CTRL-003', 'Employee Records Confidentiality Control', 'HR-FW-002'),
  ('HR-COMP-CTRL-004', 'Regular Legal Policy Review Control', 'HR-FW-002'),
  ('HR-REC-CTRL-001', 'Job Description Accuracy and Compliance Control', 'HR-FW-003'),
  ('HR-REC-CTRL-002', 'Standardized Screening and Interview Control', 'HR-FW-003'),
  ('HR-REC-CTRL-003', 'Background Check Privacy Compliance Control', 'HR-FW-003'),
  ('HR-REC-CTRL-004', 'Interview Bias Prevention Control', 'HR-FW-003'),
  ('HR-CB-CTRL-001', 'Fair and Equal Pay Control', 'HR-FW-004'),
  ('HR-CB-CTRL-002', 'Salary Review Documentation Control', 'HR-FW-004'),
  ('HR-CB-CTRL-003', 'Benefits Communication Control', 'HR-FW-004'),
  ('HR-CB-CTRL-004', 'Market Salary Benchmarking Control', 'HR-FW-004'),
  ('HR-PM-CTRL-001', 'Consistent Performance Review Documentation Control', 'HR-FW-005'),
  ('HR-PM-CTRL-002', 'Performance Improvement Plan Control', 'HR-FW-005'),
  ('HR-PM-CTRL-003', 'Performance Evaluation Criteria and Goals Control', 'HR-FW-005'),
  ('HR-PM-CTRL-004', 'Performance Review Schedule Control', 'HR-FW-005'),
  ('HR-ER-CTRL-001', 'Grievance Procedure Accessibility and Fairness Control', 'HR-FW-006'),
  ('HR-ER-CTRL-002', 'Conflict Resolution Resource Control', 'HR-FW-006'),
  ('HR-ER-CTRL-003', 'Exit Interview Control', 'HR-FW-006'),
  ('HR-ER-CTRL-004', 'Grievance Resolution Effectiveness Review Control', 'HR-FW-006'),
  ('HR-TD-CTRL-001', 'Structured Orientation and Onboarding Control', 'HR-FW-007'),
  ('HR-TD-CTRL-002', 'Training Needs and Skill Gap Alignment Control', 'HR-FW-007'),
  ('HR-TD-CTRL-003', 'Career Growth Opportunity Control', 'HR-FW-007'),
  ('HR-TD-CTRL-004', 'Training to Career Progression Linkage Control', 'HR-FW-007'),
  ('HR-POL-CTRL-001', 'Employee Handbook Currency Control', 'HR-FW-008'),
  ('HR-POL-CTRL-002', 'Policy Review and Update Control', 'HR-FW-008'),
  ('HR-POL-CTRL-003', 'Procedure Communication Control', 'HR-FW-008'),
  ('HR-POL-CTRL-004', 'Legal and Compliance Policy Review Control', 'HR-FW-008'),
  ('HR-HS-CTRL-001', 'Safety Regulation Compliance Control', 'HR-FW-009'),
  ('HR-HS-CTRL-002', 'Safety Drill and Emergency Procedure Control', 'HR-FW-009'),
  ('HR-HS-CTRL-003', 'Mental Health Resource Availability Control', 'HR-FW-009'),
  ('HR-HS-CTRL-004', 'Regular Safety Inspection Control', 'HR-FW-009'),
  ('HR-DEI-CTRL-001', 'Anti-Discrimination Policy Enforcement Control', 'HR-FW-010'),
  ('HR-DEI-CTRL-002', 'DEI Training Availability Control', 'HR-FW-010'),
  ('HR-DEI-CTRL-003', 'DEI Program Evaluation Control', 'HR-FW-010'),
  ('HR-DEI-CTRL-004', 'Employee DEI Feedback Control', 'HR-FW-010'),
  ('HR-RPT-CTRL-001', 'Audit Summary Report Control', 'HR-FW-011'),
  ('HR-RPT-CTRL-002', 'Action Item Prioritization Control', 'HR-FW-011'),
  ('HR-RPT-CTRL-003', 'Action Plan and Timeline Control', 'HR-FW-011'),
  ('HR-RPT-CTRL-004', 'Follow-Up and Corrective Action Tracking Control', 'HR-FW-011')
) AS v(code, name, framework_code)
JOIN frameworks f ON f.code = v.framework_code
ON CONFLICT (code) DO UPDATE SET
  name         = EXCLUDED.name,
  framework_id = EXCLUDED.framework_id,
  is_active    = TRUE;
