-- =========================================================================
-- Seed 18 checklist templates (one per Checklist Name in framework.xlsx)
-- plus 317 checklist items (one per row) and 317 check_checklist_items
-- rows linking each item back to its test.
--
-- All three inserts are UPSERTs so re-running keeps everything in sync if
-- the source spreadsheet changes. The xlsx covers IT (7 templates) + HR
-- (11 templates) — ECS HACCP/ISO22000 checklists are out of scope here.
-- =========================================================================

-- 1) Templates --------------------------------------------------------
INSERT INTO checklist_templates (code, name, category, is_active) VALUES
  ('TPL-IT-INFO', 'Information Security Audit Checklist', 'IT / Cybersecurity', TRUE),
  ('TPL-IT-NET', 'Network Security Audit Checklist', 'IT / Cybersecurity', TRUE),
  ('TPL-IT-CLOUD', 'Cloud Security Audit Checklist', 'IT / Cybersecurity', TRUE),
  ('TPL-IT-APP', 'Application Security Audit Checklist', 'IT / Cybersecurity', TRUE),
  ('TPL-IT-PROB', 'Problem Management Audit Checklist', 'IT / Cybersecurity', TRUE),
  ('TPL-IT-SECMGMT', 'Security Management Audit Checklist', 'IT / Cybersecurity', TRUE),
  ('TPL-IT-INC', 'Incident Management Audit Checklist', 'IT / Cybersecurity', TRUE),
  ('TPL-HR-PREP', 'HR Audit Preparation Checklist', 'HR', TRUE),
  ('TPL-HR-COMP', 'Compliance Audit Checklist', 'HR', TRUE),
  ('TPL-HR-RECRUIT', 'Recruitment and Hiring Audit Checklist', 'HR', TRUE),
  ('TPL-HR-COMPBEN', 'Compensation and Benefits Audit Checklist', 'HR', TRUE),
  ('TPL-HR-PERF', 'Performance Management Audit Checklist', 'HR', TRUE),
  ('TPL-HR-RELATIONS', 'Employee Relations Audit Checklist', 'HR', TRUE),
  ('TPL-HR-TRAIN', 'Training and Development Audit Checklist', 'HR', TRUE),
  ('TPL-HR-POLICY', 'HR Policies and Procedures Audit Checklist', 'HR', TRUE),
  ('TPL-HR-HSAFETY', 'Health and Safety Audit Checklist', 'HR', TRUE),
  ('TPL-HR-DEI', 'Diversity, Equity, and Inclusion Audit Checklist', 'HR', TRUE),
  ('TPL-HR-REPORT', 'Audit Reporting and Follow-Up Checklist', 'HR', TRUE)
ON CONFLICT (code) DO UPDATE SET
  name      = EXCLUDED.name,
  category  = EXCLUDED.category,
  is_active = TRUE;

-- 2) Items - one row per question (317 total) -----------------------
-- template_id resolved by joining checklist_templates on a name map.
-- sort_order is the 1-based row index per template (preserves the
-- spreadsheet's ordering when the page renders the items).
INSERT INTO checklist_items (template_id, code, sort_order, question, weight)
SELECT t.id, v.item_code, v.sort_order, v.question, 1 FROM (VALUES
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-001-01', 1, 'Is the access rights and permissions matrix available and updated?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-001-02', 2, 'Does each user have an assigned role, system, access level, and business owner?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-001-03', 3, 'Are privileged/admin users clearly identified?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-001-04', 4, 'Was access reviewed and approved within the required period?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-001-05', 5, 'Are leavers/transferred users removed or updated on time?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-002-01', 6, 'Are DLP incidents recorded with date, user, data type, severity, and owner?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-002-02', 7, 'Are DLP incidents investigated and categorized?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-002-03', 8, 'Are corrective actions documented and closed?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-002-04', 9, 'Are repeated DLP incidents escalated to IT Security/Management?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-003-01', 10, 'Is the document retention tracker maintained?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-003-02', 11, 'Are retention periods defined for key IT/security records?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-003-03', 12, 'Are expired records disposed securely with evidence?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-003-04', 13, 'Are exceptions to retention/disposal approved?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-004-01', 14, 'Is an encryption key inventory maintained?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-004-02', 15, 'Does each key have an owner and purpose?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-004-03', 16, 'Are key rotation dates recorded and monitored?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-004-04', 17, 'Are retired/expired keys disabled or destroyed securely?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-005-01', 18, 'Are security incidents logged in the incident tracker?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-005-02', 19, 'Does each incident have severity, owner, status, and target closure date?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-005-03', 20, 'Are incidents investigated and closed with evidence?'),
  ('TPL-IT-INFO', 'CHK-IT-INFO-CTRL-005-04', 21, 'Are major/repeated incidents escalated?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-001-01', 1, 'Is a DDoS mitigation plan/tracker maintained?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-001-02', 2, 'Are DDoS response owners and steps defined?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-001-03', 3, 'Has DDoS readiness been tested or reviewed?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-001-04', 4, 'Are open actions from DDoS readiness tracked to closure?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-002-01', 5, 'Is the network access control log maintained?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-002-02', 6, 'Are unauthorized access attempts logged and investigated?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-002-03', 7, 'Are network access changes approved?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-002-04', 8, 'Are dormant or unknown devices reviewed?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-003-01', 9, 'Is there a network security risk mitigation report?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-003-02', 10, 'Are network risks rated by impact/likelihood?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-003-03', 11, 'Are mitigation owners and due dates assigned?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-003-04', 12, 'Are overdue/high risks escalated?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-004-01', 13, 'Is network traffic monitored through a dashboard?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-004-02', 14, 'Are abnormal traffic patterns reviewed?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-004-03', 15, 'Are monitoring alerts assigned and closed?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-004-04', 16, 'Are monitoring gaps documented?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-005-01', 17, 'Is the security event correlation tracker maintained?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-005-02', 18, 'Are related events correlated into cases/incidents?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-005-03', 19, 'Are correlated events investigated and closed?'),
  ('TPL-IT-NET', 'CHK-IT-NET-CTRL-005-04', 20, 'Are critical correlated events escalated?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-001-01', 1, 'Is the cloud access control matrix maintained?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-001-02', 2, 'Are privileged cloud roles reviewed periodically?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-001-03', 3, 'Are unused/dormant cloud accounts removed or disabled?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-001-04', 4, 'Are cloud access changes approved?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-002-01', 5, 'Is cloud asset inventory maintained?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-002-02', 6, 'Does each asset have owner, environment, criticality, and status?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-002-03', 7, 'Are orphaned/unowned assets reviewed?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-002-04', 8, 'Are new assets added to inventory?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-003-01', 9, 'Is the cloud backup and recovery testing tracker maintained?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-003-02', 10, 'Are backups running according to schedule?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-003-03', 11, 'Was recovery testing performed and documented?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-003-04', 12, 'Are failed backup/recovery tests remediated?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-004-01', 13, 'Are cloud incidents logged?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-004-02', 14, 'Are cloud incidents assigned severity and owner?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-004-03', 15, 'Are containment, recovery, and closure actions documented?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-004-04', 16, 'Are cloud incidents reviewed after closure?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-005-01', 17, 'Is a cloud security configuration baseline approved?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-005-02', 18, 'Are cloud configurations compared to the baseline?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-005-03', 19, 'Are configuration deviations approved or remediated?'),
  ('TPL-IT-CLOUD', 'CHK-IT-CLOUD-CTRL-005-04', 20, 'Is the baseline reviewed after major cloud changes?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-001-01', 1, 'Is application data encryption checklist completed for critical apps?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-001-02', 2, 'Is sensitive data encrypted in transit?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-001-03', 3, 'Is sensitive data encrypted at rest where required?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-001-04', 4, 'Are encryption exceptions approved?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-002-01', 5, 'Was threat modeling completed for critical apps/changes?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-002-02', 6, 'Are threats, mitigations, owners, and residual risks documented?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-002-03', 7, 'Are unresolved high risks escalated before release?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-002-04', 8, 'Is threat model updated after major changes?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-003-01', 9, 'Is the patch and update tracker maintained?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-003-02', 10, 'Are patches risk-rated and prioritized?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-003-03', 11, 'Are critical patches completed within target timeline?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-003-04', 12, 'Are failed/deferred patches approved with reason?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-004-01', 13, 'Is the secure coding checklist used before release?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-004-02', 14, 'Are secure coding checklist items completed by developer/reviewer?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-004-03', 15, 'Are code security findings resolved before release?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-004-04', 16, 'Are exceptions documented and approved?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-005-01', 17, 'Is secure mobile app testing performed before release?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-005-02', 18, 'Are mobile app vulnerabilities documented and fixed?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-005-03', 19, 'Are release decisions approved after testing?'),
  ('TPL-IT-APP', 'CHK-IT-APP-CTRL-005-04', 20, 'Are retests performed after remediation?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-001-01', 1, 'Are known errors recorded using the KE template?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-001-02', 2, 'Does each known error include workaround and permanent fix plan?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-001-03', 3, 'Are known errors reviewed periodically?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-001-04', 4, 'Are unresolved critical known errors escalated?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-002-01', 5, 'Are major problems documented using the major problem report?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-002-02', 6, 'Are impact, timeline, root cause, and action plan documented?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-002-03', 7, 'Was management notified for major problems?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-002-04', 8, 'Was a post-problem review completed?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-003-01', 9, 'Is the problem management process approved and available?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-003-02', 10, 'Do problem records follow the defined process?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-003-03', 11, 'Are ownership and status tracked?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-003-04', 12, 'Are process exceptions documented?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-004-01', 13, 'Are problem records created for recurring or high-impact incidents?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-004-02', 14, 'Is root cause analysis documented?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-004-03', 15, 'Are corrective actions assigned with due dates?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-004-04', 16, 'Are problem records closed only after actions are verified?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-005-01', 17, 'Is ISMS policy available and referenced for security-related problems?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-005-02', 18, 'Are security-related problems escalated to ISMS/security governance?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-005-03', 19, 'Are ISMS-related actions tracked to closure?'),
  ('TPL-IT-PROB', 'CHK-IT-PROB-CTRL-005-04', 20, 'Are recurring security problems reviewed for risk treatment?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-001-01', 1, 'Is password policy approved and current?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-001-02', 2, 'Are password rules enforced in systems?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-001-03', 3, 'Are privileged accounts subject to stronger authentication?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-001-04', 4, 'Are password policy exceptions documented and approved?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-002-01', 5, 'Is backup and recovery policy approved and current?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-002-02', 6, 'Are backup responsibilities and frequencies defined?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-002-03', 7, 'Are recovery tests required and tracked?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-002-04', 8, 'Are backup failures escalated?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-003-01', 9, 'Is IT compliance management policy/process defined?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-003-02', 10, 'Are IT compliance obligations listed and assigned?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-003-03', 11, 'Are compliance reviews performed?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-003-04', 12, 'Are compliance gaps tracked to closure?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-004-01', 13, 'Is disposal and destruction policy approved?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-004-02', 14, 'Are disposed IT assets/media recorded?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-004-03', 15, 'Is data wiped or destroyed securely before disposal?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-004-04', 16, 'Are disposal vendors/approvals documented where applicable?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-005-01', 17, 'Is information transfer policy approved?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-005-02', 18, 'Are sensitive information transfers authorized?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-005-03', 19, 'Are secure transfer methods used?'),
  ('TPL-IT-SECMGMT', 'CHK-IT-SEC-CTRL-005-04', 20, 'Are transfer exceptions investigated?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-001-01', 1, 'Is the incident management guide available to IT teams?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-001-02', 2, 'Does the guide define triage, escalation, communication, and closure?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-001-03', 3, 'Are team members aware/trained on the guide?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-001-04', 4, 'Was the guide used in sampled incidents?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-002-01', 5, 'Is incident management policy approved and current?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-002-02', 6, 'Are severity levels and escalation paths defined?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-002-03', 7, 'Are incident roles and responsibilities defined?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-002-04', 8, 'Are policy exceptions documented?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-003-01', 9, 'Are major incidents recorded using the major incident report?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-003-02', 10, 'Are major incidents escalated to management?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-003-03', 11, 'Are timelines, impact, root cause, and actions documented?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-003-04', 12, 'Is post-incident review completed?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-004-01', 13, 'Are structural damage incidents recorded?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-004-02', 14, 'Are affected IT/security assets identified?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-004-03', 15, 'Are remediation and safety actions assigned?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-004-04', 16, 'Are incidents closed with evidence?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-005-01', 17, 'Are internal incidents reported using a standard report?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-005-02', 18, 'Are incidents assigned owner, severity, status, and due date?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-005-03', 19, 'Are investigations and corrective actions documented?'),
  ('TPL-IT-INC', 'CHK-IT-INC-CTRL-005-04', 20, 'Are incidents reviewed after closure?'),
  ('TPL-HR-PREP', 'CHK-0001', 1, 'Is there current evidence available for Audit Scope and Objectives Control?'),
  ('TPL-HR-PREP', 'CHK-0002', 2, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-PREP', 'CHK-0003', 3, 'Did the sampled HR records/cases comply with Audit Scope and Objectives Control?'),
  ('TPL-HR-PREP', 'CHK-0004', 4, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-PREP', 'CHK-0005', 5, 'Is there current evidence available for Audit Schedule Control?'),
  ('TPL-HR-PREP', 'CHK-0006', 6, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-PREP', 'CHK-0007', 7, 'Did the sampled HR records/cases comply with Audit Schedule Control?'),
  ('TPL-HR-PREP', 'CHK-0008', 8, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-PREP', 'CHK-0009', 9, 'Is there current evidence available for Audit Roles and Responsibilities Control?'),
  ('TPL-HR-PREP', 'CHK-0010', 10, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-PREP', 'CHK-0011', 11, 'Did the sampled HR records/cases comply with Audit Roles and Responsibilities Control?'),
  ('TPL-HR-PREP', 'CHK-0012', 12, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-PREP', 'CHK-0013', 13, 'Is there current evidence available for HR Documentation and Sensitive Data Handling Control?'),
  ('TPL-HR-PREP', 'CHK-0014', 14, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-PREP', 'CHK-0015', 15, 'Did the sampled HR records/cases comply with HR Documentation and Sensitive Data Handling Control?'),
  ('TPL-HR-PREP', 'CHK-0016', 16, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-COMP', 'CHK-0017', 1, 'Is there current evidence available for Employment Law Compliance Control?'),
  ('TPL-HR-COMP', 'CHK-0018', 2, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-COMP', 'CHK-0019', 3, 'Did the sampled HR records/cases comply with Employment Law Compliance Control?'),
  ('TPL-HR-COMP', 'CHK-0020', 4, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-COMP', 'CHK-0021', 5, 'Is there current evidence available for Benefits Legal Compliance Control?'),
  ('TPL-HR-COMP', 'CHK-0022', 6, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-COMP', 'CHK-0023', 7, 'Did the sampled HR records/cases comply with Benefits Legal Compliance Control?'),
  ('TPL-HR-COMP', 'CHK-0024', 8, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-COMP', 'CHK-0025', 9, 'Is there current evidence available for Employee Records Confidentiality Control?'),
  ('TPL-HR-COMP', 'CHK-0026', 10, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-COMP', 'CHK-0027', 11, 'Did the sampled HR records/cases comply with Employee Records Confidentiality Control?'),
  ('TPL-HR-COMP', 'CHK-0028', 12, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-COMP', 'CHK-0029', 13, 'Is there current evidence available for Regular Legal Policy Review Control?'),
  ('TPL-HR-COMP', 'CHK-0030', 14, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-COMP', 'CHK-0031', 15, 'Did the sampled HR records/cases comply with Regular Legal Policy Review Control?'),
  ('TPL-HR-COMP', 'CHK-0032', 16, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-RECRUIT', 'CHK-0033', 1, 'Is there current evidence available for Job Description Accuracy and Compliance Control?'),
  ('TPL-HR-RECRUIT', 'CHK-0034', 2, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-RECRUIT', 'CHK-0035', 3, 'Did the sampled HR records/cases comply with Job Description Accuracy and Compliance Control?'),
  ('TPL-HR-RECRUIT', 'CHK-0036', 4, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-RECRUIT', 'CHK-0037', 5, 'Is there current evidence available for Standardized Screening and Interview Control?'),
  ('TPL-HR-RECRUIT', 'CHK-0038', 6, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-RECRUIT', 'CHK-0039', 7, 'Did the sampled HR records/cases comply with Standardized Screening and Interview Control?'),
  ('TPL-HR-RECRUIT', 'CHK-0040', 8, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-RECRUIT', 'CHK-0041', 9, 'Is there current evidence available for Background Check Privacy Compliance Control?'),
  ('TPL-HR-RECRUIT', 'CHK-0042', 10, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-RECRUIT', 'CHK-0043', 11, 'Did the sampled HR records/cases comply with Background Check Privacy Compliance Control?'),
  ('TPL-HR-RECRUIT', 'CHK-0044', 12, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-RECRUIT', 'CHK-0045', 13, 'Is there current evidence available for Interview Bias Prevention Control?'),
  ('TPL-HR-RECRUIT', 'CHK-0046', 14, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-RECRUIT', 'CHK-0047', 15, 'Did the sampled HR records/cases comply with Interview Bias Prevention Control?'),
  ('TPL-HR-RECRUIT', 'CHK-0048', 16, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-COMPBEN', 'CHK-0049', 1, 'Is there current evidence available for Fair and Equal Pay Control?'),
  ('TPL-HR-COMPBEN', 'CHK-0050', 2, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-COMPBEN', 'CHK-0051', 3, 'Did the sampled HR records/cases comply with Fair and Equal Pay Control?'),
  ('TPL-HR-COMPBEN', 'CHK-0052', 4, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-COMPBEN', 'CHK-0053', 5, 'Is there current evidence available for Salary Review Documentation Control?'),
  ('TPL-HR-COMPBEN', 'CHK-0054', 6, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-COMPBEN', 'CHK-0055', 7, 'Did the sampled HR records/cases comply with Salary Review Documentation Control?'),
  ('TPL-HR-COMPBEN', 'CHK-0056', 8, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-COMPBEN', 'CHK-0057', 9, 'Is there current evidence available for Benefits Communication Control?'),
  ('TPL-HR-COMPBEN', 'CHK-0058', 10, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-COMPBEN', 'CHK-0059', 11, 'Did the sampled HR records/cases comply with Benefits Communication Control?'),
  ('TPL-HR-COMPBEN', 'CHK-0060', 12, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-COMPBEN', 'CHK-0061', 13, 'Is there current evidence available for Market Salary Benchmarking Control?'),
  ('TPL-HR-COMPBEN', 'CHK-0062', 14, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-COMPBEN', 'CHK-0063', 15, 'Did the sampled HR records/cases comply with Market Salary Benchmarking Control?'),
  ('TPL-HR-COMPBEN', 'CHK-0064', 16, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-PERF', 'CHK-0065', 1, 'Is there current evidence available for Consistent Performance Review Documentation Control?'),
  ('TPL-HR-PERF', 'CHK-0066', 2, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-PERF', 'CHK-0067', 3, 'Did the sampled HR records/cases comply with Consistent Performance Review Documentation Control?'),
  ('TPL-HR-PERF', 'CHK-0068', 4, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-PERF', 'CHK-0069', 5, 'Is there current evidence available for Performance Improvement Plan Control?'),
  ('TPL-HR-PERF', 'CHK-0070', 6, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-PERF', 'CHK-0071', 7, 'Did the sampled HR records/cases comply with Performance Improvement Plan Control?'),
  ('TPL-HR-PERF', 'CHK-0072', 8, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-PERF', 'CHK-0073', 9, 'Is there current evidence available for Performance Evaluation Criteria and Goals Control?'),
  ('TPL-HR-PERF', 'CHK-0074', 10, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-PERF', 'CHK-0075', 11, 'Did the sampled HR records/cases comply with Performance Evaluation Criteria and Goals Control?'),
  ('TPL-HR-PERF', 'CHK-0076', 12, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-PERF', 'CHK-0077', 13, 'Is there current evidence available for Performance Review Schedule Control?'),
  ('TPL-HR-PERF', 'CHK-0078', 14, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-PERF', 'CHK-0079', 15, 'Did the sampled HR records/cases comply with Performance Review Schedule Control?'),
  ('TPL-HR-PERF', 'CHK-0080', 16, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-RELATIONS', 'CHK-0081', 1, 'Is there current evidence available for Grievance Procedure Accessibility and Fairness Control?'),
  ('TPL-HR-RELATIONS', 'CHK-0082', 2, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-RELATIONS', 'CHK-0083', 3, 'Did the sampled HR records/cases comply with Grievance Procedure Accessibility and Fairness Control?'),
  ('TPL-HR-RELATIONS', 'CHK-0084', 4, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-RELATIONS', 'CHK-0085', 5, 'Is there current evidence available for Conflict Resolution Resource Control?'),
  ('TPL-HR-RELATIONS', 'CHK-0086', 6, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-RELATIONS', 'CHK-0087', 7, 'Did the sampled HR records/cases comply with Conflict Resolution Resource Control?'),
  ('TPL-HR-RELATIONS', 'CHK-0088', 8, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-RELATIONS', 'CHK-0089', 9, 'Is there current evidence available for Exit Interview Control?'),
  ('TPL-HR-RELATIONS', 'CHK-0090', 10, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-RELATIONS', 'CHK-0091', 11, 'Did the sampled HR records/cases comply with Exit Interview Control?'),
  ('TPL-HR-RELATIONS', 'CHK-0092', 12, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-RELATIONS', 'CHK-0093', 13, 'Is there current evidence available for Grievance Resolution Effectiveness Review Control?'),
  ('TPL-HR-RELATIONS', 'CHK-0094', 14, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-RELATIONS', 'CHK-0095', 15, 'Did the sampled HR records/cases comply with Grievance Resolution Effectiveness Review Control?'),
  ('TPL-HR-RELATIONS', 'CHK-0096', 16, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-TRAIN', 'CHK-0097', 1, 'Is there current evidence available for Structured Orientation and Onboarding Control?'),
  ('TPL-HR-TRAIN', 'CHK-0098', 2, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-TRAIN', 'CHK-0099', 3, 'Did the sampled HR records/cases comply with Structured Orientation and Onboarding Control?'),
  ('TPL-HR-TRAIN', 'CHK-0100', 4, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-TRAIN', 'CHK-0101', 5, 'Is there current evidence available for Training Needs and Skill Gap Alignment Control?'),
  ('TPL-HR-TRAIN', 'CHK-0102', 6, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-TRAIN', 'CHK-0103', 7, 'Did the sampled HR records/cases comply with Training Needs and Skill Gap Alignment Control?'),
  ('TPL-HR-TRAIN', 'CHK-0104', 8, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-TRAIN', 'CHK-0105', 9, 'Is there current evidence available for Career Growth Opportunity Control?'),
  ('TPL-HR-TRAIN', 'CHK-0106', 10, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-TRAIN', 'CHK-0107', 11, 'Did the sampled HR records/cases comply with Career Growth Opportunity Control?'),
  ('TPL-HR-TRAIN', 'CHK-0108', 12, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-TRAIN', 'CHK-0109', 13, 'Is there current evidence available for Training to Career Progression Linkage Control?'),
  ('TPL-HR-TRAIN', 'CHK-0110', 14, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-TRAIN', 'CHK-0111', 15, 'Did the sampled HR records/cases comply with Training to Career Progression Linkage Control?'),
  ('TPL-HR-TRAIN', 'CHK-0112', 16, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-POLICY', 'CHK-0113', 1, 'Is there current evidence available for Employee Handbook Currency Control?'),
  ('TPL-HR-POLICY', 'CHK-0114', 2, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-POLICY', 'CHK-0115', 3, 'Did the sampled HR records/cases comply with Employee Handbook Currency Control?'),
  ('TPL-HR-POLICY', 'CHK-0116', 4, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-POLICY', 'CHK-0117', 5, 'Is there current evidence available for Policy Review and Update Control?'),
  ('TPL-HR-POLICY', 'CHK-0118', 6, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-POLICY', 'CHK-0119', 7, 'Did the sampled HR records/cases comply with Policy Review and Update Control?'),
  ('TPL-HR-POLICY', 'CHK-0120', 8, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-POLICY', 'CHK-0121', 9, 'Is there current evidence available for Procedure Communication Control?'),
  ('TPL-HR-POLICY', 'CHK-0122', 10, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-POLICY', 'CHK-0123', 11, 'Did the sampled HR records/cases comply with Procedure Communication Control?'),
  ('TPL-HR-POLICY', 'CHK-0124', 12, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-POLICY', 'CHK-0125', 13, 'Is there current evidence available for Legal and Compliance Policy Review Control?'),
  ('TPL-HR-POLICY', 'CHK-0126', 14, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-POLICY', 'CHK-0127', 15, 'Did the sampled HR records/cases comply with Legal and Compliance Policy Review Control?'),
  ('TPL-HR-POLICY', 'CHK-0128', 16, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-HSAFETY', 'CHK-0129', 1, 'Is there current evidence available for Safety Regulation Compliance Control?'),
  ('TPL-HR-HSAFETY', 'CHK-0130', 2, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-HSAFETY', 'CHK-0131', 3, 'Did the sampled HR records/cases comply with Safety Regulation Compliance Control?'),
  ('TPL-HR-HSAFETY', 'CHK-0132', 4, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-HSAFETY', 'CHK-0133', 5, 'Is there current evidence available for Safety Drill and Emergency Procedure Control?'),
  ('TPL-HR-HSAFETY', 'CHK-0134', 6, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-HSAFETY', 'CHK-0135', 7, 'Did the sampled HR records/cases comply with Safety Drill and Emergency Procedure Control?'),
  ('TPL-HR-HSAFETY', 'CHK-0136', 8, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-HSAFETY', 'CHK-0137', 9, 'Is there current evidence available for Mental Health Resource Availability Control?'),
  ('TPL-HR-HSAFETY', 'CHK-0138', 10, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-HSAFETY', 'CHK-0139', 11, 'Did the sampled HR records/cases comply with Mental Health Resource Availability Control?'),
  ('TPL-HR-HSAFETY', 'CHK-0140', 12, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-HSAFETY', 'CHK-0141', 13, 'Is there current evidence available for Regular Safety Inspection Control?'),
  ('TPL-HR-HSAFETY', 'CHK-0142', 14, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-HSAFETY', 'CHK-0143', 15, 'Did the sampled HR records/cases comply with Regular Safety Inspection Control?'),
  ('TPL-HR-HSAFETY', 'CHK-0144', 16, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-DEI', 'CHK-0145', 1, 'Is there current evidence available for Anti-Discrimination Policy Enforcement Control?'),
  ('TPL-HR-DEI', 'CHK-0146', 2, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-DEI', 'CHK-0147', 3, 'Did the sampled HR records/cases comply with Anti-Discrimination Policy Enforcement Control?'),
  ('TPL-HR-DEI', 'CHK-0148', 4, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-DEI', 'CHK-0149', 5, 'Is there current evidence available for DEI Training Availability Control?'),
  ('TPL-HR-DEI', 'CHK-0150', 6, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-DEI', 'CHK-0151', 7, 'Did the sampled HR records/cases comply with DEI Training Availability Control?'),
  ('TPL-HR-DEI', 'CHK-0152', 8, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-DEI', 'CHK-0153', 9, 'Is there current evidence available for DEI Program Evaluation Control?'),
  ('TPL-HR-DEI', 'CHK-0154', 10, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-DEI', 'CHK-0155', 11, 'Did the sampled HR records/cases comply with DEI Program Evaluation Control?'),
  ('TPL-HR-DEI', 'CHK-0156', 12, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-DEI', 'CHK-0157', 13, 'Is there current evidence available for Employee DEI Feedback Control?'),
  ('TPL-HR-DEI', 'CHK-0158', 14, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-DEI', 'CHK-0159', 15, 'Did the sampled HR records/cases comply with Employee DEI Feedback Control?'),
  ('TPL-HR-DEI', 'CHK-0160', 16, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-REPORT', 'CHK-0161', 1, 'Is there current evidence available for Audit Summary Report Control?'),
  ('TPL-HR-REPORT', 'CHK-0162', 2, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-REPORT', 'CHK-0163', 3, 'Did the sampled HR records/cases comply with Audit Summary Report Control?'),
  ('TPL-HR-REPORT', 'CHK-0164', 4, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-REPORT', 'CHK-0165', 5, 'Is there current evidence available for Action Item Prioritization Control?'),
  ('TPL-HR-REPORT', 'CHK-0166', 6, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-REPORT', 'CHK-0167', 7, 'Did the sampled HR records/cases comply with Action Item Prioritization Control?'),
  ('TPL-HR-REPORT', 'CHK-0168', 8, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-REPORT', 'CHK-0169', 9, 'Is there current evidence available for Action Plan and Timeline Control?'),
  ('TPL-HR-REPORT', 'CHK-0170', 10, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-REPORT', 'CHK-0171', 11, 'Did the sampled HR records/cases comply with Action Plan and Timeline Control?'),
  ('TPL-HR-REPORT', 'CHK-0172', 12, 'Were exceptions, gaps, or missing records documented and escalated?'),
  ('TPL-HR-REPORT', 'CHK-0173', 13, 'Is there current evidence available for Follow-Up and Corrective Action Tracking Control?'),
  ('TPL-HR-REPORT', 'CHK-0174', 14, 'Does the evidence show the control was performed according to the required frequency and owner?'),
  ('TPL-HR-REPORT', 'CHK-0175', 15, 'Did the sampled HR records/cases comply with Follow-Up and Corrective Action Tracking Control?'),
  ('TPL-HR-REPORT', 'CHK-0176', 16, 'Were exceptions, gaps, or missing records documented and escalated?')
) AS v(tpl_code, item_code, sort_order, question)
JOIN checklist_templates t ON t.code = v.tpl_code
ON CONFLICT (code) DO UPDATE SET
  template_id = EXCLUDED.template_id,
  sort_order  = EXCLUDED.sort_order,
  question    = EXCLUDED.question;

-- 3) Test -> item links (317 rows) -----------------------------------
-- Each spreadsheet row pairs a test with one question item. Skips
-- silently if either side is missing (partial env).
INSERT INTO check_checklist_items (check_id, checklist_item_id)
SELECT ch.id, ci.id FROM (VALUES
  ('IT-INFO-TEST-001-01', 'CHK-IT-INFO-CTRL-001-01'),
  ('IT-INFO-TEST-001-02', 'CHK-IT-INFO-CTRL-001-02'),
  ('IT-INFO-TEST-001-01', 'CHK-IT-INFO-CTRL-001-03'),
  ('IT-INFO-TEST-001-01', 'CHK-IT-INFO-CTRL-001-04'),
  ('IT-INFO-TEST-001-02', 'CHK-IT-INFO-CTRL-001-05'),
  ('IT-INFO-TEST-002-01', 'CHK-IT-INFO-CTRL-002-01'),
  ('IT-INFO-TEST-002-01', 'CHK-IT-INFO-CTRL-002-02'),
  ('IT-INFO-TEST-002-02', 'CHK-IT-INFO-CTRL-002-03'),
  ('IT-INFO-TEST-002-02', 'CHK-IT-INFO-CTRL-002-04'),
  ('IT-INFO-TEST-003-01', 'CHK-IT-INFO-CTRL-003-01'),
  ('IT-INFO-TEST-003-01', 'CHK-IT-INFO-CTRL-003-02'),
  ('IT-INFO-TEST-003-01', 'CHK-IT-INFO-CTRL-003-03'),
  ('IT-INFO-TEST-003-01', 'CHK-IT-INFO-CTRL-003-04'),
  ('IT-INFO-TEST-004-01', 'CHK-IT-INFO-CTRL-004-01'),
  ('IT-INFO-TEST-004-01', 'CHK-IT-INFO-CTRL-004-02'),
  ('IT-INFO-TEST-004-01', 'CHK-IT-INFO-CTRL-004-03'),
  ('IT-INFO-TEST-004-01', 'CHK-IT-INFO-CTRL-004-04'),
  ('IT-INFO-TEST-005-02', 'CHK-IT-INFO-CTRL-005-01'),
  ('IT-INFO-TEST-005-01', 'CHK-IT-INFO-CTRL-005-02'),
  ('IT-INFO-TEST-005-02', 'CHK-IT-INFO-CTRL-005-03'),
  ('IT-INFO-TEST-005-02', 'CHK-IT-INFO-CTRL-005-04'),
  ('IT-NET-TEST-001-01', 'CHK-IT-NET-CTRL-001-01'),
  ('IT-NET-TEST-001-01', 'CHK-IT-NET-CTRL-001-02'),
  ('IT-NET-TEST-001-02', 'CHK-IT-NET-CTRL-001-03'),
  ('IT-NET-TEST-001-02', 'CHK-IT-NET-CTRL-001-04'),
  ('IT-NET-TEST-002-02', 'CHK-IT-NET-CTRL-002-01'),
  ('IT-NET-TEST-002-02', 'CHK-IT-NET-CTRL-002-02'),
  ('IT-NET-TEST-002-01', 'CHK-IT-NET-CTRL-002-03'),
  ('IT-NET-TEST-002-01', 'CHK-IT-NET-CTRL-002-04'),
  ('IT-NET-TEST-003-01', 'CHK-IT-NET-CTRL-003-01'),
  ('IT-NET-TEST-003-01', 'CHK-IT-NET-CTRL-003-02'),
  ('IT-NET-TEST-003-02', 'CHK-IT-NET-CTRL-003-03'),
  ('IT-NET-TEST-003-02', 'CHK-IT-NET-CTRL-003-04'),
  ('IT-NET-TEST-004-01', 'CHK-IT-NET-CTRL-004-01'),
  ('IT-NET-TEST-004-01', 'CHK-IT-NET-CTRL-004-02'),
  ('IT-NET-TEST-004-02', 'CHK-IT-NET-CTRL-004-03'),
  ('IT-NET-TEST-004-01', 'CHK-IT-NET-CTRL-004-04'),
  ('IT-NET-TEST-005-01', 'CHK-IT-NET-CTRL-005-01'),
  ('IT-NET-TEST-005-01', 'CHK-IT-NET-CTRL-005-02'),
  ('IT-NET-TEST-005-02', 'CHK-IT-NET-CTRL-005-03'),
  ('IT-NET-TEST-005-02', 'CHK-IT-NET-CTRL-005-04'),
  ('IT-CLOUD-TEST-001-01', 'CHK-IT-CLOUD-CTRL-001-01'),
  ('IT-CLOUD-TEST-001-01', 'CHK-IT-CLOUD-CTRL-001-02'),
  ('IT-CLOUD-TEST-001-02', 'CHK-IT-CLOUD-CTRL-001-03'),
  ('IT-CLOUD-TEST-001-01', 'CHK-IT-CLOUD-CTRL-001-04'),
  ('IT-CLOUD-TEST-002-01', 'CHK-IT-CLOUD-CTRL-002-01'),
  ('IT-CLOUD-TEST-002-01', 'CHK-IT-CLOUD-CTRL-002-02'),
  ('IT-CLOUD-TEST-002-01', 'CHK-IT-CLOUD-CTRL-002-03'),
  ('IT-CLOUD-TEST-002-01', 'CHK-IT-CLOUD-CTRL-002-04'),
  ('IT-CLOUD-TEST-003-01', 'CHK-IT-CLOUD-CTRL-003-01'),
  ('IT-CLOUD-TEST-003-01', 'CHK-IT-CLOUD-CTRL-003-02'),
  ('IT-CLOUD-TEST-003-02', 'CHK-IT-CLOUD-CTRL-003-03'),
  ('IT-CLOUD-TEST-003-01', 'CHK-IT-CLOUD-CTRL-003-04'),
  ('IT-CLOUD-TEST-004-02', 'CHK-IT-CLOUD-CTRL-004-01'),
  ('IT-CLOUD-TEST-004-02', 'CHK-IT-CLOUD-CTRL-004-02'),
  ('IT-CLOUD-TEST-004-02', 'CHK-IT-CLOUD-CTRL-004-03'),
  ('IT-CLOUD-TEST-004-02', 'CHK-IT-CLOUD-CTRL-004-04'),
  ('IT-CLOUD-TEST-005-02', 'CHK-IT-CLOUD-CTRL-005-01'),
  ('IT-CLOUD-TEST-005-02', 'CHK-IT-CLOUD-CTRL-005-02'),
  ('IT-CLOUD-TEST-005-02', 'CHK-IT-CLOUD-CTRL-005-03'),
  ('IT-CLOUD-TEST-005-02', 'CHK-IT-CLOUD-CTRL-005-04'),
  ('IT-APP-TEST-001-02', 'CHK-IT-APP-CTRL-001-01'),
  ('IT-APP-TEST-001-01', 'CHK-IT-APP-CTRL-001-02'),
  ('IT-APP-TEST-001-01', 'CHK-IT-APP-CTRL-001-03'),
  ('IT-APP-TEST-001-01', 'CHK-IT-APP-CTRL-001-04'),
  ('IT-APP-TEST-002-02', 'CHK-IT-APP-CTRL-002-01'),
  ('IT-APP-TEST-002-01', 'CHK-IT-APP-CTRL-002-02'),
  ('IT-APP-TEST-002-02', 'CHK-IT-APP-CTRL-002-03'),
  ('IT-APP-TEST-002-01', 'CHK-IT-APP-CTRL-002-04'),
  ('IT-APP-TEST-003-01', 'CHK-IT-APP-CTRL-003-01'),
  ('IT-APP-TEST-003-01', 'CHK-IT-APP-CTRL-003-02'),
  ('IT-APP-TEST-003-02', 'CHK-IT-APP-CTRL-003-03'),
  ('IT-APP-TEST-003-01', 'CHK-IT-APP-CTRL-003-04'),
  ('IT-APP-TEST-004-01', 'CHK-IT-APP-CTRL-004-01'),
  ('IT-APP-TEST-004-02', 'CHK-IT-APP-CTRL-004-02'),
  ('IT-APP-TEST-004-02', 'CHK-IT-APP-CTRL-004-03'),
  ('IT-APP-TEST-004-01', 'CHK-IT-APP-CTRL-004-04'),
  ('IT-APP-TEST-005-02', 'CHK-IT-APP-CTRL-005-01'),
  ('IT-APP-TEST-005-01', 'CHK-IT-APP-CTRL-005-02'),
  ('IT-APP-TEST-005-01', 'CHK-IT-APP-CTRL-005-03'),
  ('IT-APP-TEST-005-02', 'CHK-IT-APP-CTRL-005-04'),
  ('IT-PROB-TEST-001-01', 'CHK-IT-PROB-CTRL-001-01'),
  ('IT-PROB-TEST-001-01', 'CHK-IT-PROB-CTRL-001-02'),
  ('IT-PROB-TEST-001-01', 'CHK-IT-PROB-CTRL-001-03'),
  ('IT-PROB-TEST-001-02', 'CHK-IT-PROB-CTRL-001-04'),
  ('IT-PROB-TEST-002-01', 'CHK-IT-PROB-CTRL-002-01'),
  ('IT-PROB-TEST-002-01', 'CHK-IT-PROB-CTRL-002-02'),
  ('IT-PROB-TEST-002-01', 'CHK-IT-PROB-CTRL-002-03'),
  ('IT-PROB-TEST-002-02', 'CHK-IT-PROB-CTRL-002-04'),
  ('IT-PROB-TEST-003-01', 'CHK-IT-PROB-CTRL-003-01'),
  ('IT-PROB-TEST-003-01', 'CHK-IT-PROB-CTRL-003-02'),
  ('IT-PROB-TEST-003-01', 'CHK-IT-PROB-CTRL-003-03'),
  ('IT-PROB-TEST-003-01', 'CHK-IT-PROB-CTRL-003-04'),
  ('IT-PROB-TEST-004-01', 'CHK-IT-PROB-CTRL-004-01'),
  ('IT-PROB-TEST-004-01', 'CHK-IT-PROB-CTRL-004-02'),
  ('IT-PROB-TEST-004-02', 'CHK-IT-PROB-CTRL-004-03'),
  ('IT-PROB-TEST-004-02', 'CHK-IT-PROB-CTRL-004-04'),
  ('IT-PROB-TEST-005-01', 'CHK-IT-PROB-CTRL-005-01'),
  ('IT-PROB-TEST-005-02', 'CHK-IT-PROB-CTRL-005-02'),
  ('IT-PROB-TEST-005-02', 'CHK-IT-PROB-CTRL-005-03'),
  ('IT-PROB-TEST-005-01', 'CHK-IT-PROB-CTRL-005-04'),
  ('IT-SEC-TEST-001-01', 'CHK-IT-SEC-CTRL-001-01'),
  ('IT-SEC-TEST-001-02', 'CHK-IT-SEC-CTRL-001-02'),
  ('IT-SEC-TEST-001-01', 'CHK-IT-SEC-CTRL-001-03'),
  ('IT-SEC-TEST-001-01', 'CHK-IT-SEC-CTRL-001-04'),
  ('IT-SEC-TEST-002-01', 'CHK-IT-SEC-CTRL-002-01'),
  ('IT-SEC-TEST-002-01', 'CHK-IT-SEC-CTRL-002-02'),
  ('IT-SEC-TEST-002-01', 'CHK-IT-SEC-CTRL-002-03'),
  ('IT-SEC-TEST-002-02', 'CHK-IT-SEC-CTRL-002-04'),
  ('IT-SEC-TEST-003-01', 'CHK-IT-SEC-CTRL-003-01'),
  ('IT-SEC-TEST-003-02', 'CHK-IT-SEC-CTRL-003-02'),
  ('IT-SEC-TEST-003-02', 'CHK-IT-SEC-CTRL-003-03'),
  ('IT-SEC-TEST-003-01', 'CHK-IT-SEC-CTRL-003-04'),
  ('IT-SEC-TEST-004-01', 'CHK-IT-SEC-CTRL-004-01'),
  ('IT-SEC-TEST-004-01', 'CHK-IT-SEC-CTRL-004-02'),
  ('IT-SEC-TEST-004-01', 'CHK-IT-SEC-CTRL-004-03'),
  ('IT-SEC-TEST-004-01', 'CHK-IT-SEC-CTRL-004-04'),
  ('IT-SEC-TEST-005-01', 'CHK-IT-SEC-CTRL-005-01'),
  ('IT-SEC-TEST-005-01', 'CHK-IT-SEC-CTRL-005-02'),
  ('IT-SEC-TEST-005-01', 'CHK-IT-SEC-CTRL-005-03'),
  ('IT-SEC-TEST-005-01', 'CHK-IT-SEC-CTRL-005-04'),
  ('IT-INC-TEST-001-01', 'CHK-IT-INC-CTRL-001-01'),
  ('IT-INC-TEST-001-01', 'CHK-IT-INC-CTRL-001-02'),
  ('IT-INC-TEST-001-01', 'CHK-IT-INC-CTRL-001-03'),
  ('IT-INC-TEST-001-02', 'CHK-IT-INC-CTRL-001-04'),
  ('IT-INC-TEST-002-01', 'CHK-IT-INC-CTRL-002-01'),
  ('IT-INC-TEST-002-01', 'CHK-IT-INC-CTRL-002-02'),
  ('IT-INC-TEST-002-01', 'CHK-IT-INC-CTRL-002-03'),
  ('IT-INC-TEST-002-01', 'CHK-IT-INC-CTRL-002-04'),
  ('IT-INC-TEST-003-01', 'CHK-IT-INC-CTRL-003-01'),
  ('IT-INC-TEST-003-02', 'CHK-IT-INC-CTRL-003-02'),
  ('IT-INC-TEST-003-02', 'CHK-IT-INC-CTRL-003-03'),
  ('IT-INC-TEST-003-02', 'CHK-IT-INC-CTRL-003-04'),
  ('IT-INC-TEST-004-01', 'CHK-IT-INC-CTRL-004-01'),
  ('IT-INC-TEST-004-01', 'CHK-IT-INC-CTRL-004-02'),
  ('IT-INC-TEST-004-02', 'CHK-IT-INC-CTRL-004-03'),
  ('IT-INC-TEST-004-02', 'CHK-IT-INC-CTRL-004-04'),
  ('IT-INC-TEST-005-01', 'CHK-IT-INC-CTRL-005-01'),
  ('IT-INC-TEST-005-02', 'CHK-IT-INC-CTRL-005-02'),
  ('IT-INC-TEST-005-02', 'CHK-IT-INC-CTRL-005-03'),
  ('IT-INC-TEST-005-02', 'CHK-IT-INC-CTRL-005-04'),
  ('TST-PREP-001-01', 'CHK-0001'),
  ('TST-PREP-001-01', 'CHK-0002'),
  ('TST-PREP-001-02', 'CHK-0003'),
  ('TST-PREP-001-02', 'CHK-0004'),
  ('TST-PREP-002-01', 'CHK-0005'),
  ('TST-PREP-002-01', 'CHK-0006'),
  ('TST-PREP-002-02', 'CHK-0007'),
  ('TST-PREP-002-02', 'CHK-0008'),
  ('TST-PREP-003-01', 'CHK-0009'),
  ('TST-PREP-003-01', 'CHK-0010'),
  ('TST-PREP-003-02', 'CHK-0011'),
  ('TST-PREP-003-02', 'CHK-0012'),
  ('TST-PREP-004-01', 'CHK-0013'),
  ('TST-PREP-004-01', 'CHK-0014'),
  ('TST-PREP-004-02', 'CHK-0015'),
  ('TST-PREP-004-02', 'CHK-0016'),
  ('TST-COMP-001-01', 'CHK-0017'),
  ('TST-COMP-001-01', 'CHK-0018'),
  ('TST-COMP-001-02', 'CHK-0019'),
  ('TST-COMP-001-02', 'CHK-0020'),
  ('TST-COMP-002-01', 'CHK-0021'),
  ('TST-COMP-002-01', 'CHK-0022'),
  ('TST-COMP-002-02', 'CHK-0023'),
  ('TST-COMP-002-02', 'CHK-0024'),
  ('TST-COMP-003-01', 'CHK-0025'),
  ('TST-COMP-003-01', 'CHK-0026'),
  ('TST-COMP-003-02', 'CHK-0027'),
  ('TST-COMP-003-02', 'CHK-0028'),
  ('TST-COMP-004-01', 'CHK-0029'),
  ('TST-COMP-004-01', 'CHK-0030'),
  ('TST-COMP-004-02', 'CHK-0031'),
  ('TST-COMP-004-02', 'CHK-0032'),
  ('TST-REC-001-01', 'CHK-0033'),
  ('TST-REC-001-01', 'CHK-0034'),
  ('TST-REC-001-02', 'CHK-0035'),
  ('TST-REC-001-02', 'CHK-0036'),
  ('TST-REC-002-01', 'CHK-0037'),
  ('TST-REC-002-01', 'CHK-0038'),
  ('TST-REC-002-02', 'CHK-0039'),
  ('TST-REC-002-02', 'CHK-0040'),
  ('TST-REC-003-01', 'CHK-0041'),
  ('TST-REC-003-01', 'CHK-0042'),
  ('TST-REC-003-02', 'CHK-0043'),
  ('TST-REC-003-02', 'CHK-0044'),
  ('TST-REC-004-01', 'CHK-0045'),
  ('TST-REC-004-01', 'CHK-0046'),
  ('TST-REC-004-02', 'CHK-0047'),
  ('TST-REC-004-02', 'CHK-0048'),
  ('TST-CB-001-01', 'CHK-0049'),
  ('TST-CB-001-01', 'CHK-0050'),
  ('TST-CB-001-02', 'CHK-0051'),
  ('TST-CB-001-02', 'CHK-0052'),
  ('TST-CB-002-01', 'CHK-0053'),
  ('TST-CB-002-01', 'CHK-0054'),
  ('TST-CB-002-02', 'CHK-0055'),
  ('TST-CB-002-02', 'CHK-0056'),
  ('TST-CB-003-01', 'CHK-0057'),
  ('TST-CB-003-01', 'CHK-0058'),
  ('TST-CB-003-02', 'CHK-0059'),
  ('TST-CB-003-02', 'CHK-0060'),
  ('TST-CB-004-01', 'CHK-0061'),
  ('TST-CB-004-01', 'CHK-0062'),
  ('TST-CB-004-02', 'CHK-0063'),
  ('TST-CB-004-02', 'CHK-0064'),
  ('TST-PM-001-01', 'CHK-0065'),
  ('TST-PM-001-01', 'CHK-0066'),
  ('TST-PM-001-02', 'CHK-0067'),
  ('TST-PM-001-02', 'CHK-0068'),
  ('TST-PM-002-01', 'CHK-0069'),
  ('TST-PM-002-01', 'CHK-0070'),
  ('TST-PM-002-02', 'CHK-0071'),
  ('TST-PM-002-02', 'CHK-0072'),
  ('TST-PM-003-01', 'CHK-0073'),
  ('TST-PM-003-01', 'CHK-0074'),
  ('TST-PM-003-02', 'CHK-0075'),
  ('TST-PM-003-02', 'CHK-0076'),
  ('TST-PM-004-01', 'CHK-0077'),
  ('TST-PM-004-01', 'CHK-0078'),
  ('TST-PM-004-02', 'CHK-0079'),
  ('TST-PM-004-02', 'CHK-0080'),
  ('TST-ER-001-01', 'CHK-0081'),
  ('TST-ER-001-01', 'CHK-0082'),
  ('TST-ER-001-02', 'CHK-0083'),
  ('TST-ER-001-02', 'CHK-0084'),
  ('TST-ER-002-01', 'CHK-0085'),
  ('TST-ER-002-01', 'CHK-0086'),
  ('TST-ER-002-02', 'CHK-0087'),
  ('TST-ER-002-02', 'CHK-0088'),
  ('TST-ER-003-01', 'CHK-0089'),
  ('TST-ER-003-01', 'CHK-0090'),
  ('TST-ER-003-02', 'CHK-0091'),
  ('TST-ER-003-02', 'CHK-0092'),
  ('TST-ER-004-01', 'CHK-0093'),
  ('TST-ER-004-01', 'CHK-0094'),
  ('TST-ER-004-02', 'CHK-0095'),
  ('TST-ER-004-02', 'CHK-0096'),
  ('TST-TD-001-01', 'CHK-0097'),
  ('TST-TD-001-01', 'CHK-0098'),
  ('TST-TD-001-02', 'CHK-0099'),
  ('TST-TD-001-02', 'CHK-0100'),
  ('TST-TD-002-01', 'CHK-0101'),
  ('TST-TD-002-01', 'CHK-0102'),
  ('TST-TD-002-02', 'CHK-0103'),
  ('TST-TD-002-02', 'CHK-0104'),
  ('TST-TD-003-01', 'CHK-0105'),
  ('TST-TD-003-01', 'CHK-0106'),
  ('TST-TD-003-02', 'CHK-0107'),
  ('TST-TD-003-02', 'CHK-0108'),
  ('TST-TD-004-01', 'CHK-0109'),
  ('TST-TD-004-01', 'CHK-0110'),
  ('TST-TD-004-02', 'CHK-0111'),
  ('TST-TD-004-02', 'CHK-0112'),
  ('TST-POL-001-01', 'CHK-0113'),
  ('TST-POL-001-01', 'CHK-0114'),
  ('TST-POL-001-02', 'CHK-0115'),
  ('TST-POL-001-02', 'CHK-0116'),
  ('TST-POL-002-01', 'CHK-0117'),
  ('TST-POL-002-01', 'CHK-0118'),
  ('TST-POL-002-02', 'CHK-0119'),
  ('TST-POL-002-02', 'CHK-0120'),
  ('TST-POL-003-01', 'CHK-0121'),
  ('TST-POL-003-01', 'CHK-0122'),
  ('TST-POL-003-02', 'CHK-0123'),
  ('TST-POL-003-02', 'CHK-0124'),
  ('TST-POL-004-01', 'CHK-0125'),
  ('TST-POL-004-01', 'CHK-0126'),
  ('TST-POL-004-02', 'CHK-0127'),
  ('TST-POL-004-02', 'CHK-0128'),
  ('TST-HS-001-01', 'CHK-0129'),
  ('TST-HS-001-01', 'CHK-0130'),
  ('TST-HS-001-02', 'CHK-0131'),
  ('TST-HS-001-02', 'CHK-0132'),
  ('TST-HS-002-01', 'CHK-0133'),
  ('TST-HS-002-01', 'CHK-0134'),
  ('TST-HS-002-02', 'CHK-0135'),
  ('TST-HS-002-02', 'CHK-0136'),
  ('TST-HS-003-01', 'CHK-0137'),
  ('TST-HS-003-01', 'CHK-0138'),
  ('TST-HS-003-02', 'CHK-0139'),
  ('TST-HS-003-02', 'CHK-0140'),
  ('TST-HS-004-01', 'CHK-0141'),
  ('TST-HS-004-01', 'CHK-0142'),
  ('TST-HS-004-02', 'CHK-0143'),
  ('TST-HS-004-02', 'CHK-0144'),
  ('TST-DEI-001-01', 'CHK-0145'),
  ('TST-DEI-001-01', 'CHK-0146'),
  ('TST-DEI-001-02', 'CHK-0147'),
  ('TST-DEI-001-02', 'CHK-0148'),
  ('TST-DEI-002-01', 'CHK-0149'),
  ('TST-DEI-002-01', 'CHK-0150'),
  ('TST-DEI-002-02', 'CHK-0151'),
  ('TST-DEI-002-02', 'CHK-0152'),
  ('TST-DEI-003-01', 'CHK-0153'),
  ('TST-DEI-003-01', 'CHK-0154'),
  ('TST-DEI-003-02', 'CHK-0155'),
  ('TST-DEI-003-02', 'CHK-0156'),
  ('TST-DEI-004-01', 'CHK-0157'),
  ('TST-DEI-004-01', 'CHK-0158'),
  ('TST-DEI-004-02', 'CHK-0159'),
  ('TST-DEI-004-02', 'CHK-0160'),
  ('TST-RPT-001-01', 'CHK-0161'),
  ('TST-RPT-001-01', 'CHK-0162'),
  ('TST-RPT-001-02', 'CHK-0163'),
  ('TST-RPT-001-02', 'CHK-0164'),
  ('TST-RPT-002-01', 'CHK-0165'),
  ('TST-RPT-002-01', 'CHK-0166'),
  ('TST-RPT-002-02', 'CHK-0167'),
  ('TST-RPT-002-02', 'CHK-0168'),
  ('TST-RPT-003-01', 'CHK-0169'),
  ('TST-RPT-003-01', 'CHK-0170'),
  ('TST-RPT-003-02', 'CHK-0171'),
  ('TST-RPT-003-02', 'CHK-0172'),
  ('TST-RPT-004-01', 'CHK-0173'),
  ('TST-RPT-004-01', 'CHK-0174'),
  ('TST-RPT-004-02', 'CHK-0175'),
  ('TST-RPT-004-02', 'CHK-0176')
) AS v(test_code, item_code)
JOIN checks          ch ON ch.code = v.test_code
JOIN checklist_items ci ON ci.code = v.item_code
ON CONFLICT DO NOTHING;
